### ISSUE TITLE
python errors in construct

### ISSUE THREAD

**Issue by abazhaniuk** [ANSSI-FR/bootcode_parser#3]
$ python bootcode_parser.py --type MBR --input test_data/mbr_*
Traceback (most recent call last):
  File "bootcode_parser.py", line 124, in <module>
    class MasterBootRecord(BootRecord):
  File "bootcode_parser.py", line 126, in MasterBootRecord
    construct.HexDumpAdapter(construct.Bytes("bootloader_code", 440)),
AttributeError: 'module' object has no attribute 'HexDumpAdapter'

**Comment by sc-anssi** [comment]
It seems that you have a more recent version of python-construct than the one needed by bootcode_parser (which is python-construct = 2.5.2).
Construct API changed quite dramatically with version 2.8 and I have to update bootcode_parser... eventually. In the mean time, you can pip install python-construct in a version that is compatible (ie. 2.5.x).
Sorry about that.

**Comment by PracaGrande** [comment]
Had the same issue but installing the proper version fixes it as mentioned before.
$ sudo pip install construct==2.5.2
